import { Business, BlogPost } from "./types";

// NOTE: Images use Lorem Picsum (picsum.photos), a free service that serves real
// (non-AI-generated) stock photography, seeded deterministically per business.
// Swap these for curated Pexels/Unsplash photos of each real business before launch.
const img = (seed: string, n: number) =>
  Array.from({ length: n }, (_, i) => `https://picsum.photos/seed/${seed}-${i}/900/650`);

export const businesses: Business[] = [
  {
    slug: "the-hound-house-cafe",
    name: "The Hound House Cafe",
    category: "Restaurants & Cafes",
    tier: "pet-inclusive",
    description: "A dog-loving cafe with a full pup menu and a fenced patio to play in.",
    longDescription:
      "The Hound House Cafe was built from the ground up for pet parents. Alongside its espresso bar and all-day brunch menu, it offers a dedicated pup menu, water and treat stations at every table, and a fenced outdoor patio where dogs can safely roam off-leash while you enjoy your coffee.",
    city: "Austin",
    state: "TX",
    address: "1420 S Congress Ave, Austin, TX 78704",
    phone: "(512) 555-0142",
    website: "https://example.com",
    hours: "Mon–Sun: 7:00 AM – 6:00 PM",
    petPolicy: "Pets welcome throughout the patio and designated indoor pet-friendly zone.",
    serviceAnimalPolicy: "Service animals welcome everywhere, no restrictions.",
    esaPolicy: "Emotional support animals welcome on the patio.",
    amenities: ["Water bowls", "Pet menu", "Fenced patio", "Waste bags provided", "Treat station"],
    images: img("hound-house", 4),
    rating: 4.8,
    reviewCount: 214,
    verifiedDate: "March 2026",
    lat: 30.2504,
    lng: -97.7495,
    reviews: [
      {
        id: "r1",
        author: "Marisol P.",
        rating: 5,
        date: "June 2026",
        comment: "My golden retriever has his own regular seat here. Staff know him by name!",
      },
      {
        id: "r2",
        author: "Devon K.",
        rating: 5,
        date: "May 2026",
        comment: "Best patio in the city for a coffee date with your dog.",
      },
    ],
  },
  {
    slug: "wagging-tail-inn",
    name: "Wagging Tail Inn",
    category: "Hotels & Accommodations",
    tier: "pet-inclusive",
    description: "Boutique pet-inclusive hotel with in-room pet beds and a dog run.",
    longDescription:
      "Wagging Tail Inn is a boutique hotel designed around traveling with pets. Every room comes with a pet bed, bowls, and a welcome treat. The property includes a fenced dog run, an on-call pet sitting service, and staff trained in pet first aid.",
    city: "Asheville",
    state: "NC",
    address: "220 Biltmore Ave, Asheville, NC 28801",
    phone: "(828) 555-0199",
    website: "https://example.com",
    hours: "Front desk: 24/7",
    petPolicy: "No weight limit, no breed restrictions, no additional pet fee.",
    serviceAnimalPolicy: "Service animals welcome in all areas, no documentation required.",
    esaPolicy: "ESAs welcome with prior notice to front desk.",
    amenities: ["In-room pet beds", "Fenced dog run", "Pet sitting", "Pet first aid trained staff", "Walking trails nearby"],
    images: img("wagging-tail", 4),
    rating: 4.9,
    reviewCount: 331,
    verifiedDate: "January 2026",
    lat: 35.5951,
    lng: -82.5515,
    reviews: [
      {
        id: "r1",
        author: "Alan R.",
        rating: 5,
        date: "April 2026",
        comment: "They treated our senior dog like royalty. Will always book here.",
      },
    ],
  },
  {
    slug: "riverside-bark-park",
    name: "Riverside Bark Park",
    category: "Parks & Outdoor Spaces",
    tier: "pets-allowed",
    description: "Open riverside dog park with agility equipment and shaded seating.",
    longDescription:
      "Riverside Bark Park spans five acres along the river with separate areas for large and small dogs, agility equipment, and shaded seating for owners. Waste stations are maintained daily by the city parks department.",
    city: "Denver",
    state: "CO",
    address: "1800 Riverfront Pkwy, Denver, CO 80202",
    phone: "(303) 555-0110",
    website: "https://example.com",
    hours: "Daily: 6:00 AM – 10:00 PM",
    petPolicy: "Dogs must be leashed except in designated off-leash zones. Owners must clean up after pets.",
    serviceAnimalPolicy: "Service animals permitted throughout the park.",
    esaPolicy: "Treated as standard pets; leash rules apply.",
    amenities: ["Off-leash zone", "Agility equipment", "Waste stations", "Shaded seating", "Water fountains"],
    images: img("bark-park", 4),
    rating: 4.5,
    reviewCount: 128,
    verifiedDate: "February 2026",
    lat: 39.7565,
    lng: -104.9987,
    reviews: [
      {
        id: "r1",
        author: "Priya S.",
        rating: 4,
        date: "March 2026",
        comment: "Great space, gets crowded on weekends but well maintained.",
      },
    ],
  },
  {
    slug: "paws-and-claws-boutique",
    name: "Paws & Claws Boutique",
    category: "Retail & Shopping",
    tier: "pet-friendly",
    description: "Pet supply boutique that welcomes leashed pets to shop with you.",
    longDescription:
      "Paws & Claws Boutique carries a curated selection of pet food, toys, and accessories. Leashed, well-behaved pets are welcome to browse the store with their owners, and staff are happy to answer questions about the store's pet policy.",
    city: "Portland",
    state: "OR",
    address: "980 NW 23rd Ave, Portland, OR 97210",
    phone: "(503) 555-0176",
    website: "https://example.com",
    hours: "Mon–Sat: 10:00 AM – 7:00 PM, Sun: 11:00 AM – 5:00 PM",
    petPolicy: "Leashed pets welcome throughout the store.",
    serviceAnimalPolicy: "Service animals always welcome.",
    esaPolicy: "ESAs welcome, leash required.",
    amenities: ["Designated pet area", "Water bowls", "Treat samples", "Staff trained on policy"],
    images: img("paws-boutique", 4),
    rating: 4.6,
    reviewCount: 89,
    verifiedDate: "April 2026",
    lat: 45.5301,
    lng: -122.6976,
    reviews: [
      {
        id: "r1",
        author: "Jamie L.",
        rating: 5,
        date: "June 2026",
        comment: "Staff let my cat sniff every toy before we bought it. So sweet.",
      },
    ],
  },
  {
    slug: "furry-friends-grooming-studio",
    name: "Furry Friends Grooming Studio",
    category: "Groomers & Pet Services",
    tier: "pet-inclusive",
    description: "Full-service grooming, daycare, and boarding with pet-trained staff.",
    longDescription:
      "Furry Friends Grooming Studio offers grooming, daycare, and boarding from a team trained in low-stress handling techniques. The studio maintains detailed emergency protocols and works closely with a nearby veterinary partner.",
    city: "Chicago",
    state: "IL",
    address: "3312 N Southport Ave, Chicago, IL 60657",
    phone: "(773) 555-0134",
    website: "https://example.com",
    hours: "Mon–Sat: 8:00 AM – 6:00 PM",
    petPolicy: "By appointment; all pets must have current vaccination records on file.",
    serviceAnimalPolicy: "Service animals accommodated with staff trained on ADA regulations.",
    esaPolicy: "ESAs accepted for grooming and boarding services.",
    amenities: ["Low-stress handling", "Emergency protocols", "Daycare webcams", "Climate-controlled boarding"],
    images: img("grooming-studio", 4),
    rating: 4.9,
    reviewCount: 176,
    verifiedDate: "May 2026",
    lat: 41.9403,
    lng: -87.6638,
    reviews: [
      {
        id: "r1",
        author: "Nora T.",
        rating: 5,
        date: "June 2026",
        comment: "The only groomer my anxious rescue dog has ever been calm with.",
      },
    ],
  },
  {
    slug: "cornerstone-veterinary-clinic",
    name: "Cornerstone Veterinary Clinic",
    category: "Veterinary & Healthcare",
    tier: "pet-inclusive",
    description: "Full-service animal hospital with 24/7 emergency care.",
    longDescription:
      "Cornerstone Veterinary Clinic provides preventive care, surgery, dental, and round-the-clock emergency services. The clinic's fear-free certified staff focus on reducing stress for both pets and their people.",
    city: "Nashville",
    state: "TN",
    address: "615 Church St, Nashville, TN 37219",
    phone: "(615) 555-0188",
    website: "https://example.com",
    hours: "24/7 Emergency Care",
    petPolicy: "Open to all species; walk-ins accepted for emergencies.",
    serviceAnimalPolicy: "Service animals prioritized for same-day scheduling when needed.",
    esaPolicy: "ESAs treated as standard patients.",
    amenities: ["24/7 emergency care", "Fear-free certified", "On-site pharmacy", "Digital imaging"],
    images: img("vet-clinic", 4),
    rating: 4.7,
    reviewCount: 402,
    verifiedDate: "February 2026",
    lat: 36.1657,
    lng: -86.7844,
    reviews: [
      {
        id: "r1",
        author: "Chris B.",
        rating: 5,
        date: "May 2026",
        comment: "They saved our cat's life on a Sunday night. Forever grateful.",
      },
    ],
  },
  {
    slug: "yappy-hour-pet-events",
    name: "Yappy Hour Pet Events",
    category: "Events & Activities",
    tier: "pet-friendly",
    description: "Monthly pet meetups, adoption fairs, and outdoor movie nights.",
    longDescription:
      "Yappy Hour Pet Events hosts monthly community meetups including adoption fairs, pet-friendly outdoor movie nights, and seasonal festivals, all held at partner venues with clear pet policies posted in advance.",
    city: "San Diego",
    state: "CA",
    address: "Liberty Station, San Diego, CA 92106",
    phone: "(619) 555-0155",
    website: "https://example.com",
    hours: "Events posted monthly",
    petPolicy: "Leashed pets welcome at all events; policies vary slightly by venue.",
    serviceAnimalPolicy: "Service animals welcome at every event.",
    esaPolicy: "ESAs welcome, leash required.",
    amenities: ["Water stations", "Waste bags", "Vet volunteers on-site", "Adoption partners"],
    images: img("yappy-hour", 4),
    rating: 4.6,
    reviewCount: 71,
    verifiedDate: "June 2026",
    lat: 32.7492,
    lng: -117.2151,
    reviews: [
      {
        id: "r1",
        author: "Elena V.",
        rating: 5,
        date: "June 2026",
        comment: "Adopted our second dog at one of their events. Wonderful community.",
      },
    ],
  },
  {
    slug: "petcab-rides",
    name: "PetCab Rides",
    category: "Transportation",
    tier: "pets-allowed",
    description: "On-demand rideshare service with pet-safe vehicles and carriers.",
    longDescription:
      "PetCab Rides offers on-demand transportation with seat covers, safety harnesses, and loaner carriers for pet parents without a car. Drivers complete a pet-handling orientation before joining the platform.",
    city: "Seattle",
    state: "WA",
    address: "Citywide service",
    phone: "(206) 555-0121",
    website: "https://example.com",
    hours: "Daily: 6:00 AM – 11:00 PM",
    petPolicy: "All pets must be leashed or carriered during the ride.",
    serviceAnimalPolicy: "Service animals ride free of additional fees.",
    esaPolicy: "ESAs accepted with standard carrier policy.",
    amenities: ["Seat covers", "Safety harnesses", "Loaner carriers", "Pet-trained drivers"],
    images: img("petcab", 4),
    rating: 4.4,
    reviewCount: 58,
    verifiedDate: "March 2026",
    lat: 47.6062,
    lng: -122.3321,
    reviews: [
      {
        id: "r1",
        author: "Tom H.",
        rating: 4,
        date: "April 2026",
        comment: "Great for vet trips when I don't have my own car.",
      },
    ],
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: "top-10-pet-friendly-beaches-2026",
    title: "10 Pet-Friendly Beaches Worth the Road Trip in 2026",
    excerpt:
      "From off-leash stretches in California to shaded coves in Florida, here are the coastlines your dog will love as much as you do.",
    content: [
      "Summer road trips are better with a co-pilot who has four paws. We combed through verified FurFinds locations to find beaches that go beyond simply 'tolerating' dogs.",
      "Look for beaches with fresh-water rinse stations, shaded parking, and clearly posted leash rules — all signs of a well-managed pet-friendly destination.",
      "Whichever coast you choose, always check seasonal restrictions before you go; many beaches limit off-leash hours during peak summer months.",
    ],
    category: "Pet-Friendly Travel",
    author: "FurFinds Editorial",
    date: "June 12, 2026",
    image: img("blog-beaches", 1)[0],
  },
  {
    slug: "how-cornerstone-vet-earned-pet-inclusive",
    title: "Behind the Badge: How Cornerstone Veterinary Clinic Earned Pet-Inclusive Status",
    excerpt:
      "A look inside the verification process with one of our newest Pet-Inclusive partners.",
    content: [
      "Earning FurFinds' top tier isn't just about having a pet-friendly sign on the door. Cornerstone Veterinary Clinic went through our full documentation and site-visit process.",
      "Their fear-free certification, 24/7 emergency protocols, and staff training on service animal regulations pushed them into Pet-Inclusive territory.",
      "We spoke to their lead veterinarian about what the process looks like from the inside.",
    ],
    category: "Business Spotlights",
    author: "FurFinds Editorial",
    date: "May 28, 2026",
    image: img("blog-vet", 1)[0],
  },
  {
    slug: "first-time-flying-with-your-dog",
    title: "Flying With Your Dog for the First Time: A Practical Checklist",
    excerpt:
      "Everything to sort out two weeks, two days, and two hours before your flight.",
    content: [
      "Air travel with pets can feel overwhelming the first time. Start with your airline's specific pet policy — cabin weight limits vary widely.",
      "Two weeks out: schedule a vet visit for a health certificate if required by your destination.",
      "Day of travel: arrive early, bring familiar bedding, and avoid feeding a large meal right before the flight.",
    ],
    category: "Pet Care Tips",
    author: "Kashmere Miller",
    date: "May 14, 2026",
    image: img("blog-flying", 1)[0],
  },
  {
    slug: "furfinds-3-tier-system-explained",
    title: "The FurFinds 3-Tier System, Explained",
    excerpt:
      "What separates 'Pets Allowed' from 'Pet-Inclusive'? We break down our verification standards.",
    content: [
      "Not all pet-friendly claims are created equal. That's why FurFinds built a proprietary three-tier verification system.",
      "Pets Allowed means basic access with clear policies. Pet-Friendly adds amenities and trained staff. Pet-Inclusive means the business was designed around pets from the ground up.",
      "Every business is re-verified periodically to make sure standards hold up over time.",
    ],
    category: "Industry News",
    author: "FurFinds Editorial",
    date: "April 30, 2026",
    image: img("blog-tiers", 1)[0],
  },
  {
    slug: "reading-a-pet-policy-like-a-pro",
    title: "How to Read a Pet Policy Like a Pro",
    excerpt:
      "The fine print matters. Here's what to look for before you show up with your pet in tow.",
    content: [
      "A good pet policy should answer three questions: where can my pet go, what's expected of me, and what happens if something goes wrong.",
      "Watch for vague language like 'pet-friendly atmosphere' without specifics — that's often a sign the policy hasn't been tested.",
      "FurFinds requires every verified business to publish a clear, specific pet policy as part of the application process.",
    ],
    category: "Pet Care Tips",
    author: "FurFinds Editorial",
    date: "April 9, 2026",
    image: img("blog-policy", 1)[0],
  },
  {
    slug: "spotlight-wagging-tail-inn",
    title: "Business Spotlight: Wagging Tail Inn's Boutique Approach to Pet Travel",
    excerpt:
      "How a small Asheville hotel became one of our highest-rated Pet-Inclusive stays.",
    content: [
      "Wagging Tail Inn started as a single bed-and-breakfast with one very good rule: pets stay free, always.",
      "Today, the inn's fenced dog run and pet first-aid-trained staff have made it a go-to stop for cross-country road trippers.",
      "We asked the owners what they'd tell other hoteliers considering going pet-inclusive.",
    ],
    category: "Business Spotlights",
    author: "FurFinds Editorial",
    date: "March 22, 2026",
    image: img("blog-inn", 1)[0],
  },
];

export function getBusinessBySlug(slug: string) {
  return businesses.find((b) => b.slug === slug);
}

export function getPostBySlug(slug: string) {
  return blogPosts.find((p) => p.slug === slug);
}
